# -*- python -*-
def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    source = [
        'passive_aggressive.cpp',
        'passive_aggressive_1.cpp',
        'passive_aggressive_2.cpp',
        'regression_factory.cpp',
        'perceptron.cpp',
        'confidence_weighted.cpp',
        'arow.cpp',
        'normal_herd.cpp',
        'nearest_neighbor_regression.cpp',
        'nearest_neighbor_regression_util.cpp',
        'linear_regression.cpp',
        'inverted_index_regression.cpp',
        'cosine_similarity_regression.cpp',
        'euclidean_distance_regression.cpp'
        ]
    headers = [
          'regression_base.hpp',
          'regression_factory.hpp',
          ]
    use = ['jubatus_util']

    bld.core_sources.extend(bld.add_prefix(source))
    bld.core_headers.extend(bld.add_prefix(headers))
    bld.core_use.extend(use)

    def make_test(s):
        bld.program(
            features = 'gtest',
            source = s,
            target = s[0: s.rfind('.')],
            includes = '.',
            use = ['jubatus_util', 'jubatus_core']
            )

    test_source = [
        'regression_test.cpp',
        'regression_factory_test.cpp',
        ]
    for s in test_source:
        make_test(s)

