# -*- python -*-
import Options

subdirs = "util core"

def options(opt):
  opt.recurse(subdirs)

def configure(conf):
  conf.recurse(subdirs)

def build(bld):
  bld.recurse(subdirs)
  bld.install_files('${PREFIX}/include/jubatus',
                    ['core_config.hpp'])
