import Options

subdirs = "common anomaly burst classifier driver framework fv_converter graph recommender regression stat storage nearest_neighbor table clustering unlearner wordcount third_party"

def options(opt):
  opt.recurse(subdirs)

def configure(conf):
  conf.recurse(subdirs)

def build(bld):
  bld.recurse(subdirs)
